# ==============================================================================
# ==============================================================================
glint_site_testen:            true
glint_url_abs:                "" # Moet gevuld worden bij deploy, bijv. www.bolle.nl, ZONDER / op einde
glint_url_rel:                "" # Meestal leeg, indien gevuld , bijv. www.bolle.nl/, MET / op einde
# ==============================================================================
# Gems
plugins_dir:
  - jekyll-paginate
  - jekyll-babel
babel_js_extensions:          'esXXX6'  
# ==============================================================================
# Build settings
markdown: kramdown
# ==============================================================================
# ==============================================================================
